# Generated by Django 5.0.7 on 2024-07-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0002_location_created_at_location_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='visitors',
            field=models.IntegerField(default=100),
        ),
    ]
