# Generated by Django 5.0.7 on 2024-07-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0003_location_visitors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='location',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='ads',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
