# Generated by Django 5.0.7 on 2024-07-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0004_remove_location_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
