# Generated by Django 5.0.7 on 2024-07-29 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0008_alter_ads_lat_alter_ads_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('views', models.IntegerField(default=0)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.location')),
            ],
            options={
                'db_table': 'tbl_daily_reports',
            },
        ),
    ]
